###deployment.yaml###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}-{{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        ports:
        - containerPort: {{ .Values.service.TargetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: {{ .Values.service.Port}}
      protocol: TCP
      targetPort: {{ .Values.service.TargetPort}}
  type: {{ .Values.service.Type}}
